### PR TITLE
Url history duplicate fix

### PR DESCRIPTION
**Pull request by MDinler**
## Description

Duplicate urls are now removed from the list. AND the "Recent Session" button is removed because it had no use. The "Import from last session" button is renamed to "Import Recent Session"

## Important files to review

videoframegrid.py for url fix and main.ui for the buttons

### CODE REVIEW

**Comment by MDinler** [comment]
Fixes #132

**Comment by MDinler** [comment]
Can we order the history list if we use a set? Because the most recent url should be on the top of the list, or what do you Think?

**Comment by mictab** [comment]
If keeping the order is important then I think we should go what with you have.

**Comment by mictab** [comment]
@MDinler Are you ready to merge?

**Pull request merged**
