### PR TITLE
Add support for macOS

### PR DESCRIPTION
**Pull request by mictab**
## Description
macOS support wooooo! 🎉 

## Important files to review
`videoframes.py`

## Screenshots
screen shot 2017-05-13 at 12 55 01

## See also
Doesn't work on master due to getting NoneType like in https://github.com/kaszim/desktop-stream-viewer/pull/112, but this should work when that is fixed. I tested this on the commits before using the pip package for VLC.

### CODE REVIEW

**Comment by mictab** [comment]
Works if you use the `vlc.py` file we used before instead of the pip module.

**Comment by kaszim** [comment]
Can you try it now? With the changes in master.

**Comment by mictab** [comment]
@kaszim Crashes, still get NoneType.

**Comment by mictab** [comment]
@svenanderzen @kaszim Readded vlc.py as discussed.

**Pull request merged**
